Fix adding item to cart without sufficient stock available
adrienshen/saleor-storefront pull request #15
Opened 2020-05-29 13:19 UTC by nikunjsdev

Fix adding item to cart without sufficient stock available

2020-05-30 06:05 UTC, adrienshen commented
I don't see this on the `collections/cabinets/Q29sbGVjdGlvbjo0/dark-elegance/cabinet-parts` page. Did you implement?

2020-06-01 10:42 UTC, nikunjsdev commented
> I don't see this on the `collections/cabinets/Q29sbGVjdGlvbjo0/dark-elegance/cabinet-parts` page. Did you implement?

I have implemented this in `collections/cabinets/Q29sbGVjdGlvbjo0/dark-elegance/cabinet-parts` page and pushed the code.

2020-06-03 00:35 UTC, adrienshen commented
@nikunjsdev Can you add screenshots of the relevant screens?

2020-06-03 00:55 UTC, zshanhui requested changes

2020-06-03 00:55 UTC, adrienshen commented on src/components/Collection/CollectionBlock.tsx
>          <Link to={`/collections/cabinets/${collect.id}/${collect.slug}`}>
Change `collect` to `collection`

Either use 1 letter: `c` for short lambda functions like `collections.map(c => c.namae)` or use the full name to keep naming consistent.

2020-06-03 00:55 UTC, adrienshen commented on src/components/OverlayManager/Cart/ProductList.tsx
> +    stock: 0,
The stock comes from CMS backend, I don't see any reason it should be set to `0` or need an `id`. I think you might be over complicating things here. Please ask me if you have any doubts.

2020-06-03 00:55 UTC, adrienshen commented on src/components/OverlayManager/Cart/ProductList.tsx
> +        <span>Colored Parrot Cushion</span>
Why is this hardcoded?

2020-06-03 00:55 UTC, adrienshen commented on src/components/OverlayManager/Cart/ProductList.tsx
> +          }
I'm not sure what you're doing here, but it doesn't look right. Overcomplicated.

You don't need `localStorage` for this.

You just need to compare the item quantity with the backends' stock number. It's really simple.

2020-06-03 00:57 UTC, adrienshen commented
@nikunjsdev Hey, I've reviewed this PR and I think you're overcomplicating this task and going in the wrong direction. Let's put this on hold first, and I will assign you some more UI related tasks as it looks like you handle those better.

2020-06-03 01:05 UTC, zshanhui requested changes

2020-06-03 01:05 UTC, adrienshen commented on src/components/OverlayManager/Cart/ProductList.tsx
> +}
No need for `localStorage` here.

2020-07-03 06:06 UTC, closed without merging